# Generated by Django 5.2 on 2025-07-24 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturer_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField()),
                ('student_number', models.CharField(default='', max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='lecturer_data.department')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department', 'student_number'), name='unique_number_per_dept')],
            },
        ),
    ]
