# Generated by Django 5.2 on 2025-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='lecturer_tc',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
