# Generated by Django 5.2 on 2025-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='building',
            name='unique_block_per_dept',
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('department', 'name'), name='unique_block_per_dept'),
        ),
    ]
