# Generated by Django 5.2 on 2025-07-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0002_remove_building_unique_block_per_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='lecturer_data.building'),
        ),
    ]
