# Generated by Django 5.2 on 2025-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0003_alter_classroom_building'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('code', 'department'), name='unique_code_per_department'),
        ),
    ]
