# Generated by Django 5.2 on 2025-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0004_lecture_unique_code_per_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='explicit_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
