# Generated by Django 5.2 on 2025-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0005_alter_lecture_explicit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
