# Generated by Django 5.2 on 2025-07-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0006_alter_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='lecturer_data.lecturer'),
        ),
    ]
