# Generated by Django 5.2 on 2025-07-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0007_alter_section_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='is_taken_rollcall',
        ),
    ]
