# Generated by Django 5.2 on 2025-07-28 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0008_remove_hours_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturer_data.classroom'),
        ),
    ]
