# Generated by Django 5.2 on 2025-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_data', '0010_hours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='order',
            field=models.CharField(default='', max_length=2),
        ),
    ]
