# Generated by Django 5.2 on 2025-07-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturer_data', '0001_initial'),
        ('student_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_list', to='lecturer_data.section')),
                ('students', models.ManyToManyField(related_name='enrolled_lists', to='student_data.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('hour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_list', to='lecturer_data.hours')),
                ('student_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_lists', to='yoklama_data.studentlist')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('attendance_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='yoklama_data.attendancelist')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_data.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attendance_list', 'student'), name='unique_list_per_student')],
            },
        ),
    ]
