# Generated by Django 5.2 on 2025-08-02 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturer_data', '0013_alter_lecturer_user'),
        ('student_data', '0003_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_list', to='lecturer_data.section')),
                ('students', models.ManyToManyField(related_name='enrolled_lists', to='student_data.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_taken_rollcall', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_lists', to='lecturer_data.hours')),
                ('student_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_lists', to='yoklama_data.studentlist')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='yoklama_data.attendancelist')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student_data.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attendance_list', 'student'), name='unique_list_per_student')],
            },
        ),
    ]
