# Generated by Django 5.2 on 2025-07-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoklama_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelist',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='is_taken_rollcall',
            field=models.BooleanField(default=False),
        ),
    ]
