# Generated by Django 5.2 on 2025-08-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoklama_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelist',
            name='attendance_date',
        ),
    ]
