# Generated by Django 5.2 on 2025-08-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoklama_data', '0002_remove_attendancelist_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='attended',
            new_name='is_attended',
        ),
    ]
